In [1]:
import sys

sys.path.append("../")

import pennylane as qml
import pennylane.numpy as np
from main import *

np.random.seed(0)  # For reproducibility

In [2]:
X1 = X_op( [1,-1], [0] )
X2 = X_op( [2,-3], [0] )
P1 = P_op( [1,-1], [0] )
P2 = P_op( [3,-4], [0] )

In [3]:
X = X1+X2
X.eigvals()

[0]
[0]
0 0 (2,)


tensor([ 3., -4.], requires_grad=True)

In [4]:
PX = X + P1 
PX.terms()[0].eigvals()

tensor([ 3., -4.], requires_grad=True)

In [5]:
PX2 = PX + X 
PX2.terms()[0].eigvals()

[0]
[0]
0 0 (2,)


tensor([ 6., -8.], requires_grad=True)

In [6]:
P = P1 + P2
P.eigvals()

[0]
[0]
0 0 (2,)


tensor([ 4., -5.], requires_grad=True)

In [7]:
XXPP = X1 + X2 + P1 + P2 
XXPP

[0]
[0]
0 0 (2,)
[0]
[0]
0 0 (2,)
  (1) [Hermitian0]


In [8]:
XXPP.terms()[0].eigvals()

tensor([ 3., -4.], requires_grad=True)

In [9]:
XXPP.terms()[1].eigvals()

tensor([ 4., -5.], requires_grad=True)

In [10]:
X2 = X_op( [2,-3], [0] )
X3 = X_op( [1,-1], [1] )
X4 = X_op( [1,-1,1,2], [1,2] )


In [11]:
np.diag( np.kron(X2.matrix(),np.eye(2)) 
        + np.kron(np.eye(2),X3.matrix()) 
        )

tensor([ 3.,  1., -2., -4.], requires_grad=True)

In [12]:
(X2 + X3 ).eigvals()

[0]
[1]
0 1 (2, 2)


tensor([ 3.,  3., -4., -4.], requires_grad=True)

In [13]:
np.diag( np.kron(X2.matrix(),np.eye(4)) 
        + np.kron(np.kron(np.eye(2),X3.matrix()), np.eye(2) ) 
        + np.kron(np.eye(2),X4.matrix() ) 
)

tensor([ 4.,  2.,  2.,  3., -1., -3., -3., -2.], requires_grad=True)

In [14]:
(X2 + X3 + X4).eigvals()

[0]
[1]
0 1 (2, 2)
[0, 1]
[1, 2]
1 2 (2, 2, 2)


ValueError: axes don't match array

In [ ]:
np.diag( np.kron(X2.matrix(),np.eye(4)) 
        + np.kron(np.kron(np.eye(2),X3.matrix()), np.eye(2) ) )

tensor([ 3.,  3.,  1.,  1., -2., -2., -4., -4.], requires_grad=True)

In [ ]:
np.diag( np.kron(np.eye(2),X4.matrix() ) )

tensor([ 1., -1.,  1.,  2.,  1., -1.,  1.,  2.], requires_grad=True)